/// features › directorio › animales › infrastructure › isar › isar_care — Isar schemas for the care calendar.
///
/// Until these existed, [CareRule], [CareRecord] and [ScheduledCare] lived only
/// in memory: `CareScheduler` could compute the next due date but nothing kept
/// it, so every schedule was lost when the app closed.
library;

import 'package:isar/isar.dart';
import 'package:libretapp/core/models/stable_record_model.dart';
import 'package:libretapp/features/directorio/animales/domain/entities/care_record.dart';
import 'package:libretapp/features/directorio/animales/domain/entities/care_rule.dart';
import 'package:libretapp/features/directorio/animales/domain/entities/scheduled_care.dart';
import 'package:libretapp/features/directorio/animales/domain/enums/sex.dart';
import 'package:libretapp/features/directorio/animales/domain/enums/species.dart';

part 'isar_care.g.dart';

@collection
class IsarCareRule implements StableRecordModel {
  @override
  Id id = Isar.autoIncrement;

  /// The rule's domain id doubles as its stable uuid: rules are identified by
  /// it everywhere (records, schedules) and it must survive a backup merge.
  @override
  @Index(unique: true, replace: true)
  String recordUuid = '';

  late String name;
  late String type;
  late int intervalDays;
  int? minIntervalDays;
  int? maxIntervalDays;
  int? leadTimeDays;

  /// Null means the rule applies to every species or sex.
  String? species;
  String? sex;

  int? minAgeMonths;
  int? maxAgeMonths;
  bool mandatory = true;

  /// Lets a breeder retire a default rule without deleting it, so the
  /// preload does not simply bring it back.
  bool active = true;
}

@collection
class IsarCareRecord implements StableRecordModel {
  @override
  Id id = Isar.autoIncrement;

  @override
  @Index(unique: true, replace: true)
  String recordUuid = '';

  @Index()
  late String animalUuid;

  @Index()
  late String ruleId;

  late String type;
  late DateTime performedAt;
  String? notes;
  String? performedBy;
}

@collection
class IsarScheduledCare implements StableRecordModel {
  @override
  Id id = Isar.autoIncrement;

  @override
  @Index(unique: true, replace: true)
  String recordUuid = '';

  @Index()
  late String animalUuid;

  late String ruleId;
  late String type;

  @Index()
  late DateTime dueAt;

  DateTime? remindAt;
  bool done = false;
  bool autoGenerated = true;
}

extension IsarCareRuleMapper on IsarCareRule {
  CareRule toEntity() => CareRule(
    id: recordUuid,
    name: name,
    type: CareType.values.byName(type),
    intervalDays: intervalDays,
    minIntervalDays: minIntervalDays,
    maxIntervalDays: maxIntervalDays,
    leadTimeDays: leadTimeDays,
    species: species == null ? null : Species.values.byName(species!),
    sex: sex == null ? null : Sex.values.byName(sex!),
    minAgeMonths: minAgeMonths,
    maxAgeMonths: maxAgeMonths,
    mandatory: mandatory,
  );
}

extension CareRuleToIsar on CareRule {
  IsarCareRule toIsar({bool active = true}) => IsarCareRule()
    ..recordUuid = id
    ..name = name
    ..type = type.name
    ..intervalDays = intervalDays
    ..minIntervalDays = minIntervalDays
    ..maxIntervalDays = maxIntervalDays
    ..leadTimeDays = leadTimeDays
    ..species = species?.name
    ..sex = sex?.name
    ..minAgeMonths = minAgeMonths
    ..maxAgeMonths = maxAgeMonths
    ..mandatory = mandatory
    ..active = active;
}

extension IsarCareRecordMapper on IsarCareRecord {
  CareRecord toEntity() => CareRecord(
    id: recordUuid,
    animalId: animalUuid,
    ruleId: ruleId,
    type: CareType.values.byName(type),
    performedAt: performedAt,
    notes: notes,
    performedBy: performedBy,
  );
}

extension CareRecordToIsar on CareRecord {
  IsarCareRecord toIsar() => IsarCareRecord()
    ..recordUuid = id
    ..animalUuid = animalId
    ..ruleId = ruleId
    ..type = type.name
    ..performedAt = performedAt
    ..notes = notes
    ..performedBy = performedBy;
}

extension IsarScheduledCareMapper on IsarScheduledCare {
  ScheduledCare toEntity() => ScheduledCare(
    id: recordUuid,
    animalId: animalUuid,
    ruleId: ruleId,
    type: CareType.values.byName(type),
    dueAt: dueAt,
    remindAt: remindAt,
    done: done,
    autoGenerated: autoGenerated,
  );
}

extension ScheduledCareToIsar on ScheduledCare {
  IsarScheduledCare toIsar() => IsarScheduledCare()
    ..recordUuid = id
    ..animalUuid = animalId
    ..ruleId = ruleId
    ..type = type.name
    ..dueAt = dueAt
    ..remindAt = remindAt
    ..done = done
    ..autoGenerated = autoGenerated;
}
