import 'package:libretapp/features/animales/domain/entities/care_record.dart';
import 'package:libretapp/features/animales/domain/entities/care_rule.dart';
import 'package:libretapp/features/animales/domain/entities/scheduled_care.dart';

/// Servicio in-memory para calcular la siguiente tarea basada en reglas.
class CareScheduler {
  const CareScheduler();

  ScheduledCare? nextDue({
    required String animalId,
    required CareRule rule,
    required DateTime now,
    CareRecord? lastRecord,
  }) {
    final lastDate = lastRecord?.performedAt;
    if (lastDate == null) {
      return _build(animalId, rule, dueAt: now, remindAt: now);
    }

    final due = lastDate.add(Duration(days: rule.intervalDays));
    final remind = rule.leadTimeDays != null
        ? due.subtract(Duration(days: rule.leadTimeDays!))
        : null;
    if (due.isBefore(now)) {
      // overdue; schedule immediately
      return _build(animalId, rule, dueAt: now, remindAt: now);
    }
    return _build(animalId, rule, dueAt: due, remindAt: remind ?? due);
  }

  ScheduledCare _build(
    String animalId,
    CareRule rule, {
    required DateTime dueAt,
    DateTime? remindAt,
    bool autoGenerated = true,
  }) {
    return ScheduledCare(
      id: '${animalId}_${rule.id}_${dueAt.millisecondsSinceEpoch}',
      animalId: animalId,
      ruleId: rule.id,
      type: rule.type,
      dueAt: dueAt,
      remindAt: remindAt ?? dueAt,
      autoGenerated: autoGenerated,
    );
  }
}
