/// Drives the "Cuidados" tab: registering a pending task must create a
/// CareRecord and push the task out of the pending list once the parent
/// reloads — the same loop the Agenda relies on to stop reminding.
///
/// Uses an in-memory [CareRepository] rather than the real Isar-backed one:
/// testWidgets runs inside a fake-async clock that real Isar I/O (native FFI
/// callbacks on their own OS thread) never resolves within, so this stays a
/// plain-Dart fake — the same reason `registro_reproduccion_flow_test.dart`
/// fakes its repositories instead of hitting Isar directly.
library;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:libretapp/features/directorio/animales/domain/animal_domain.dart';
import 'package:libretapp/features/directorio/animales/domain/entities/care_record.dart';
import 'package:libretapp/features/directorio/animales/domain/entities/care_rule.dart';
import 'package:libretapp/features/directorio/animales/domain/entities/scheduled_care.dart';
import 'package:libretapp/features/directorio/animales/domain/enums/production_stage.dart';
import 'package:libretapp/features/directorio/animales/domain/enums/production_system.dart';
import 'package:libretapp/features/directorio/animales/domain/repositories/care_repository.dart';
import 'package:libretapp/features/directorio/animales/domain/services/care_calendar_service.dart';
import 'package:libretapp/features/directorio/animales/widgets/care_tab.dart';
import 'package:libretapp/features/directorio/animales/widgets/detail_helpers.dart';

AnimalEntity _cow() {
  final now = DateTime(2026, 1, 1);
  return AnimalEntity(
    uuid: 'vaca-1',
    earTagNumber: 'V-1',
    species: Species.cattle,
    category: Category.cow,
    lifeStage: LifeStage.cow,
    sex: Sex.female,
    breed: 'Brahman',
    birthDate: DateTime(2023, 1, 1),
    ageMonths: 36,
    healthStatus: HealthStatus.good,
    vaccinated: false,
    dewormed: false,
    hasVitamins: false,
    hasChronicIssues: false,
    reproductiveStatus: ReproductiveStatus.active,
    productionPurpose: ProductionPurpose.breeding,
    productionStage: ProductionStage.reproductive,
    productionSystem: ProductionSystem.extensive,
    underObservation: false,
    requiresAttention: false,
    riskLevel: RiskLevel.none,
    gallery: const [],
    status: AnimalStatus.active,
    synced: true,
    creationDate: now,
    lastUpdateDate: now,
  );
}

/// Plain in-memory stand-in, just enough for [CareCalendarService] and the
/// widget under test — no Isar, no real I/O.
class _InMemoryCareRepository implements CareRepository {
  final Map<String, CareRule> _rules = {};
  final Set<String> _retiredIds = {};
  final List<CareRecord> _records = [];
  final Map<String, ScheduledCare> _schedules = {};

  @override
  Future<List<CareRule>> getRules() async =>
      _rules.values.where((r) => !_retiredIds.contains(r.id)).toList();

  @override
  Future<Set<String>> getAllRuleIds() async => _rules.keys.toSet();

  @override
  Future<void> saveRule(CareRule rule) async => _rules[rule.id] = rule;

  @override
  Future<void> retireRule(String ruleId) async => _retiredIds.add(ruleId);

  @override
  Future<List<CareRecord>> getRecordsForAnimal(String animalUuid) async =>
      _records.where((r) => r.animalId == animalUuid).toList();

  @override
  Future<Map<String, CareRecord>> getLatestRecordsByRule(
    String animalUuid,
  ) async {
    final byRule = <String, CareRecord>{};
    for (final record in _records.where((r) => r.animalId == animalUuid)) {
      final current = byRule[record.ruleId];
      if (current == null || record.performedAt.isAfter(current.performedAt)) {
        byRule[record.ruleId] = record;
      }
    }
    return byRule;
  }

  @override
  Future<void> saveRecord(CareRecord record) async => _records.add(record);

  @override
  Future<List<ScheduledCare>> getPending({DateTime? until}) async {
    final tasks = _schedules.values.where((s) => !s.done);
    if (until == null) return tasks.toList();
    return tasks.where((s) => !s.dueAt.isAfter(until)).toList();
  }

  @override
  Future<List<ScheduledCare>> getPendingForAnimal(String animalUuid) async =>
      _schedules.values
          .where((s) => s.animalId == animalUuid && !s.done)
          .toList();

  @override
  Future<void> saveSchedules(List<ScheduledCare> schedules) async {
    for (final schedule in schedules) {
      _schedules[schedule.id] = schedule;
    }
  }

  @override
  Future<void> markDone(String scheduleId) async {
    final current = _schedules[scheduleId];
    if (current != null) _schedules[scheduleId] = current.copyWith(done: true);
  }

  @override
  Future<void> clearGeneratedFor(String animalUuid) async {
    _schedules.removeWhere(
      (_, s) => s.animalId == animalUuid && s.autoGenerated,
    );
  }

  @override
  Future<void> deleteAllForAnimal(String animalUuid) async {
    _records.removeWhere((r) => r.animalId == animalUuid);
    _schedules.removeWhere((_, s) => s.animalId == animalUuid);
  }
}

void main() {
  testWidgets('registering a pending task creates a record and notifies', (
    tester,
  ) async {
    final careRepo = _InMemoryCareRepository();
    await careRepo.saveRule(
      const CareRule(
        id: 'r1',
        name: 'Vacunación anual',
        type: CareType.vaccination,
        intervalDays: 365,
        species: Species.cattle,
      ),
    );

    final animal = _cow();
    final pending = await CareCalendarService(
      careRepo,
    ).regenerateFor(animal, now: DateTime(2026, 3, 1));
    expect(pending, hasLength(1));

    var changed = false;
    final data = DetailData(
      animal: animal,
      weights: const [],
      reproductions: const [],
      productions: const [],
      health: const [],
      commercial: const [],
      movements: const [],
      costs: const [],
      milkingRecords: const [],
      carePending: pending,
      careRecords: const [],
      careRules: {for (final r in await careRepo.getRules()) r.id: r},
    );

    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: CareTab(
            data: data,
            careRepo: careRepo,
            onChanged: () => changed = true,
          ),
        ),
      ),
    );
    await tester.pumpAndSettle();

    expect(find.text('Vacunación anual'), findsOneWidget);
    expect(find.text('Registrar'), findsOneWidget);

    await tester.tap(find.text('Registrar'));
    await tester.pumpAndSettle();

    expect(find.text('Guardar'), findsOneWidget);
    await tester.tap(find.text('Guardar'));
    await tester.pumpAndSettle();

    expect(changed, isTrue);
    final records = await careRepo.getRecordsForAnimal('vaca-1');
    expect(records, hasLength(1));
    expect(records.single.ruleId, 'r1');

    final stillPending = await careRepo.getPendingForAnimal('vaca-1');
    expect(stillPending, hasLength(1));
    expect(
      stillPending.single.dueAt.isAfter(
        DateTime.now().add(const Duration(days: 300)),
      ),
      isTrue,
      reason:
          'the due date moved about a year out, not gone — the rule '
          'still applies, it is just not due for a while',
    );
  });

  testWidgets('past care shows up in the history section', (tester) async {
    final careRepo = _InMemoryCareRepository();
    await careRepo.saveRule(
      const CareRule(
        id: 'r1',
        name: 'Baño garrapaticida',
        type: CareType.tickBath,
        intervalDays: 21,
        species: Species.cattle,
      ),
    );

    final animal = _cow();
    await careRepo.saveRecord(
      CareRecord(
        id: 'c1',
        animalId: animal.uuid,
        ruleId: 'r1',
        type: CareType.tickBath,
        performedAt: DateTime(2026, 2, 20),
        notes: 'Sin novedad',
      ),
    );

    // Nothing pending here on purpose: the point of this test is the history
    // section, and a regenerated schedule would also read "Baño
    // garrapaticida" in Pendientes, making the finder ambiguous.
    final data = DetailData(
      animal: animal,
      weights: const [],
      reproductions: const [],
      productions: const [],
      health: const [],
      commercial: const [],
      movements: const [],
      costs: const [],
      milkingRecords: const [],
      carePending: const [],
      careRecords: await careRepo.getRecordsForAnimal(animal.uuid),
      careRules: {for (final r in await careRepo.getRules()) r.id: r},
    );

    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: CareTab(data: data, careRepo: careRepo, onChanged: () {}),
        ),
      ),
    );
    await tester.pumpAndSettle();

    expect(find.textContaining('Historial (1)'), findsOneWidget);
    expect(find.text('Baño garrapaticida'), findsOneWidget);
    expect(find.textContaining('Sin novedad'), findsOneWidget);
  });
}
