import 'package:equatable/equatable.dart';
import 'package:libretapp/features/directorio/animales/domain/entities/care_rule.dart';

/// Tarea programada para un animal derivada de una regla.
class ScheduledCare extends Equatable {
  final String id;
  final String animalId;
  final String ruleId;
  final CareType type;
  final DateTime dueAt;
  final DateTime? remindAt;
  final bool done;
  final bool autoGenerated;

  const ScheduledCare({
    required this.id,
    required this.animalId,
    required this.ruleId,
    required this.type,
    required this.dueAt,
    this.remindAt,
    this.done = false,
    this.autoGenerated = true,
  });

  ScheduledCare copyWith({
    String? id,
    String? animalId,
    String? ruleId,
    CareType? type,
    DateTime? dueAt,
    DateTime? remindAt,
    bool? done,
    bool? autoGenerated,
  }) {
    return ScheduledCare(
      id: id ?? this.id,
      animalId: animalId ?? this.animalId,
      ruleId: ruleId ?? this.ruleId,
      type: type ?? this.type,
      dueAt: dueAt ?? this.dueAt,
      remindAt: remindAt ?? this.remindAt,
      done: done ?? this.done,
      autoGenerated: autoGenerated ?? this.autoGenerated,
    );
  }

  @override
  List<Object?> get props => [
    id,
    animalId,
    ruleId,
    type,
    dueAt,
    remindAt,
    done,
    autoGenerated,
  ];
}
