/// features > directorio > animales > domain > animal_domain — barrel for animal domain layer.
library;

export 'entities/animal_entity.dart';
export 'entities/commercial_record.dart';
export 'entities/cost_record.dart';
export 'entities/health_record.dart';
export 'entities/movement_record.dart';
export 'entities/production_record.dart';
export 'entities/reproduction_record.dart';
export 'entities/weight_record.dart';
export 'enums/animal_status.dart';
export 'enums/category.dart';
export 'enums/health_status.dart';
export 'enums/life_stage.dart';
export 'enums/origin_type.dart';
export 'enums/production_purpose.dart';
export 'enums/reproductive_status.dart';
export 'enums/risk_level.dart';
export 'enums/sex.dart';
export 'enums/species.dart';
export 'models/animal_registration_seed.dart';
export 'models/approximate_age.dart';
export 'services/animal_purpose_indicators.dart';
export 'services/animal_registration_policy.dart';
export 'services/animal_registration_normalizer.dart';
export 'services/animal_taxonomy.dart';
export 'services/animal_presentation.dart';
export 'services/pedigree_service.dart';
export 'services/reproduction_scheduler.dart';
export 'services/reproductive_kpi_service.dart';
